name: Continous Deployment Releases Workflow
on:
  push:
    tags:
      - ^\d+\.\d*.?\d*$
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/ci
      - name: Archive bundle
        run: tar -zcvf venus-html5-app.tar.gz dist/
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - name: Upload Release Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./venus-html5-app.tar.gz
          asset_name: venus-html5-app.tar.gz
          asset_content_type: application/zip
